# Generated by Django 5.1.3 on 2024-11-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_telegram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_whatsapp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_youtube',
        ),
    ]
